### PR TITLE
fix: bump last tonic v0.10 version before release

### PR DESCRIPTION
**Pull request by fenollp**
@mechiru cc https://github.com/mechiru/google-api-proto/pull/20#issuecomment-1954699434

cc https://crates.io/crates/google-api-proto/1.515.0

### CODE REVIEW

**Comment by fenollp** [comment]
#24 may be a better fix?

**Comment by mechiru** [comment]
@fenollp Thanks! This problem fixed by #24

**Comment by mechiru** [comment]
Sorry for late reply🙏

**Comment by mechiru** [comment]
The version 1.156.0 is now available!

**Pull request closed without merging**
